/**
  * @copyright Copyright (c) 2022, HiSilicon (Shanghai) Technologies Co., Ltd. All rights reserved.
  * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
  * following conditions are met:
  * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
  * disclaimer.
  * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
  * following disclaimer in the documentation and/or other materials provided with the distribution.
  * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
  * products derived from this software without specific prior written permission.
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
  * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
  * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  * @file      key_sample.c
  * @author    MCU Application Team
  * @brief     Key sample code
  * @details   This file provides firmware functions to manage the following
  *            functionalities of the common function sample.
  *             + Key sample functions
  */

/* Includes ------------------------------------------------------------------ */
#include "key_sample.h"

/* Private macro ------------------------------------------------------------- */
#define BOARD_KEY_SAMPLE_BAUDRATE 115200

/* Private variables --------------------------------------------------------- */
static TIMER_Handle g_timer1; /**< Timer handle */

static void TIMER1_Init(void);
void Key0LongPress(void);
void Key0ShortPress(void);
void Key1LongPress(void);
void Key1ShortPress(void);

/**
  * @brief Timer initialization function, it is automatically generated by the code generation tool.
  */
static void TIMER1_Init(void)
{
    g_timer1.baseAddress = TIMER1;
    g_timer1.load = 1; /* Set timer value immediately */
    g_timer1.bgLoad = 1;
    g_timer1.mode = TIMER_MODE_RUN_PERIODIC; /* Run in period mode */
    g_timer1.prescaler = 0; /* don't frequency division */
    g_timer1.interruptEn = 1; /* trigger interrupt enable */
    g_timer1.size = 1; /* 1 for 32bit, 0 for 16bit */
    g_timer1.irqNum = IRQ_TIMER1;
    IRQ_SetPriority(g_timer1.irqNum, 1); /* set timer0 interrupt priority to 1, 1~7 */
    IRQ_EnableN(g_timer1.irqNum); /* timer interrupt enable */
    HAL_TIMER_Init(&g_timer1);
}

/**
  * @brief Pin 0 long press binding functions.
  */
void Key0LongPress()
{
    DBG_PRINTF("pin0 long\r\n");
}

/**
  * @brief Pin 0 short press binding functions.
  */
void Key0ShortPress()
{
    DBG_PRINTF("pin0 short\r\n");
}

/**
  * @brief Pin 1 long press binding functions.
  */
void Key1LongPress()
{
    DBG_PRINTF("pin1 long\r\n");
}

/**
  * @brief Pin 1 short press binding functions.
  */
void Key1ShortPress()
{
    DBG_PRINTF("pin1 short\r\n");
}

/**
  * @brief Key press detection example.
  * @return int Execution result.
  */
int BOARD_KEY_Sample(void)
{
    DBG_UartPrintInit(BOARD_KEY_SAMPLE_BAUDRATE);
    IRQ_Enable();
    IRQ_Init();
    TIMER1_Init();

    BOARD_KEY_Init(&g_timer1, 100, 1000); /* 100 : 100ms, 1000 : 1000ms */

    BOARD_KEY_Register(GPIO3, GPIO_PIN_0, Key0LongPress, Key0ShortPress);
    BOARD_KEY_Register(GPIO3, GPIO_PIN_1, Key1LongPress, Key1ShortPress);

    HAL_TIMER_Start(&g_timer1);

    while (1) {
    }
    return 0;
}