/**
  * @copyright Copyright (c) 2022, HiSilicon (Shanghai) Technologies Co., Ltd. All rights reserved.
  * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
  * following conditions are met:
  * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
  * disclaimer.
  * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
  * following disclaimer in the documentation and/or other materials provided with the distribution.
  * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
  * products derived from this software without specific prior written permission.
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
  * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
  * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  * @file      matrixkey_sample.c
  * @author    MCU Application Team
  * @brief     Matrix key sample code
  * @details   This file provides firmware functions to manage the following
  *            functionalities of the common function sample.
  *             + Matrix key sample functions
  */

/* Includes ------------------------------------------------------------------ */
#include "matrixkey_sample.h"

/* Private macro ------------------------------------------------------------- */
#define BOARD_MATRIXKEY_SAMPLE_BAUDRATE 115200

/* Private variables --------------------------------------------------------- */
static TIMER_Handle g_timer1; /**< Timer handle */

static void TIMER1_Init(void);
void MKey0Func(void);
void MKey1Func(void);

/**
  * @brief Timer initialization function, it is automatically generated by the code generation tool.
  */
static void TIMER1_Init(void)
{
    g_timer1.baseAddress = TIMER1;
    g_timer1.load = 1; /* Set timer value immediately */
    g_timer1.bgLoad = 1;
    g_timer1.mode = TIMER_MODE_RUN_PERIODIC; /* Run in period mode */
    g_timer1.prescaler = 0; /* don't frequency division */
    g_timer1.interruptEn = 1; /* trigger interrupt enable */
    g_timer1.size = 1; /* 1 for 32bit, 0 for 16bit */
    g_timer1.irqNum = IRQ_TIMER1;
    IRQ_SetPriority(g_timer1.irqNum, 1); /* set timer0 interrupt priority to 1, 1~7 */
    IRQ_EnableN(g_timer1.irqNum); /* timer interrupt enable */
    HAL_TIMER_Init(&g_timer1);
}

/**
  * @brief Key 0 binding function.
  */
void MKey0Func()
{
    DBG_PRINTF("key0 press\r\n");
}

/**
  * @brief Key 1 binding function.
  */
void MKey1Func()
{
    DBG_PRINTF("key1 press\r\n");
}

/**
  * @brief Matrix keys sample.
  * @return int Execution result.
  */
int BOARD_MATRIXKEY_Sample(void)
{
    DBG_UartPrintInit(BOARD_MATRIXKEY_SAMPLE_BAUDRATE);
    DBG_PRINTF("get in main! \r\n");
    IRQ_Enable();
    IRQ_Init();
    TIMER1_Init();

    BOARD_MKEY_Init(&g_timer1, 100); /* 100 : 100ms. */

    BOARD_MKEY_ConfigOutputPin(GPIO1, GPIO_PIN_0, 0); /* 0 : index value. */
    BOARD_MKEY_ConfigOutputPin(GPIO1, GPIO_PIN_1, 1); /* 1 : index value. */
    BOARD_MKEY_ConfigOutputPin(GPIO1, GPIO_PIN_2, 2); /* 2 : index value. */
    BOARD_MKEY_ConfigOutputPin(GPIO1, GPIO_PIN_3, 3); /* 3 : index value. */

    BOARD_MKEY_ConfigInputPin(GPIO3, GPIO_PIN_0, 0); /* 0 : index value. */
    BOARD_MKEY_ConfigInputPin(GPIO3, GPIO_PIN_1, 1); /* 1 : index value. */
    BOARD_MKEY_ConfigInputPin(GPIO0, GPIO_PIN_2, 2); /* 2 : index value. */
    BOARD_MKEY_ConfigInputPin(GPIO0, GPIO_PIN_3, 3); /* 3 : index value. */

    BOARD_MKEY_RegisterKeyFun(0, MKey0Func);
    BOARD_MKEY_RegisterKeyFun(1, MKey1Func);

    HAL_TIMER_Start(&g_timer1);
    while (1) {
#if (BOARD_MKEY_SCHEME_NUMBER == BOARD_MKEY_SCHEME_NUMBER_TWO)
        BOARD_MKEY_SCAN_KEY();
#endif
    }

    return 0;
}